name: Build Debug Apk

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: [ubuntu-latest]
    steps:
      # Setup JDK
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Caching
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Grant executable permission to ./gradlew
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # Build apk
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      # Upload apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      # Release debug build apk only
      - name: Releasing using Hub
        uses: ShaunLWM/action-release-debugapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          APP_FOLDER: app
          RELEASE_TITLE: Release Debug Build
